//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zawody_projekt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZawodyEntities : DbContext
    {
        public ZawodyEntities()
            : base("name=ZawodyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<trenerzy> trenerzy { get; set; }
        public virtual DbSet<uczestnictwo> uczestnictwo { get; set; }
        public virtual DbSet<zawodnicy> zawodnicy { get; set; }
        public virtual DbSet<zawody> zawody { get; set; }
    }
}
