//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zawody_projekt
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class zawody
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public zawody()
        {
            this.uczestnictwo = new ObservableCollection<uczestnictwo>();
        }
    
        public int id_zawodow { get; set; }
        public string nazwa { get; set; }
        public System.DateTime data_za { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<uczestnictwo> uczestnictwo { get; set; }
    }
}
